### ISSUE TITLE
Wayland Support

### ISSUE THREAD

**Issue by SamHSmith** [mauikit/mauikit#1]
Just downloaded index and noticed that it's running in xwayland. Are there plans to add wayland support?

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Is this currently true? I am not certain of how to verify this.

**Comment by SamHSmith** [comment]
Run it inside a wayland environment. Ex Sway. If you can copy paste between the application and an app you know is using wayland then both are using wayland. You can't copy paste between apps running inside xwayland and normal wayland apps.

**Comment by UriHerrera** [comment]
Please file bugs at https://invent.kde.org/groups/maui/-/issues
