### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by ShalokShalom** [mauikit/mauikit#11]
Hi there :)

How is mauikit to build?

Thanks

**Comment by ShalokShalom** [comment]
I try to build it with qmake: mauikit_export.h is missing.

**Comment by milohr** [comment]
Hi @ShalokShalom 
There are two ways to use MauiKit, it can be installed system wide, with just:
mkdir build && cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/usr
make
sudo make install
and the other way is to statically link it to a project.
To build the maui apps on gnu linux the best way is to first build and install mauikit and then build the specific app.

For example for vvave, you install mauikit and then just use cmake to also build vvave.

Let me know if you have any issues.

**Comment by ShalokShalom** [comment]
Thanks for your reply. This happens on Cmake: https://pastebin.com/cSCW8XJv

**Comment by milohr** [comment]
You might be missing the ecm package (extra cmake modules)

**Comment by ShalokShalom** [comment]
As said, it builds now. And yes, I know that extra-cmake-modules is required. Which is why I think its sane to provide actual build instructions, so that other people can test easily.

**Comment by FabioLolix** [comment]
@ShalokShalom @kaisfm

https://github.com/FabioLolix/PKGBUILD/blob/master/mauikit-git/PKGBUILD
https://aur.archlinux.org/packages/mauikit-git/

For vvave
https://github.com/FabioLolix/PKGBUILD/blob/master/vvave-git/PKGBUILD
https://aur.archlinux.org/packages/vvave-git/

@milohr What is the license of mauikit? GPL3?

**Comment by milohr** [comment]
@fabiololix yes. I need to add the license file.

**Comment by yoruba-codigy** [comment]
> Hi @ShalokShalom
> There are two ways to use MauiKit, it can be installed system wide, with just:
> mkdir build && cd build
> cmake .. -DCMAKE_INSTALL_PREFIX=/usr
> make
> sudo make install
> and the other way is to statically link it to a project.
> To build the maui apps on gnu linux the best way is to first build and install mauikit and then build the specific app.
> 
> For example for vvave, you install mauikit and then just use cmake to also build vvave.
> 
> Let me know if you have any issues.

Hi, I Have A Whole Lot Of Errors Trying To Build maui, i keep getting cmake errors

**Comment by milohr** [comment]
The mauikit repo has been moved to kde gitlab instance at least invent.kde.org/kde/mauikit

Let me know what are the issues building mauikit. They might only be missing dependencies. If you are building under Debian based I can list the dependencies packages needed to build it.

**Comment by ShalokShalom** [comment]
You can archive this repo and link the new location in the Readme.
